### ISSUE TITLE
cannot build on Windows 10 + VS2019

### ISSUE THREAD

**Issue by xianyukang** [enlyze/Wizard-2020#9]
![image](https://user-images.githubusercontent.com/24707226/141236607-9f3f25b0-a463-42ee-af7b-f25a2a081df2.png)

**Comment by ColinFinck** [comment]
Can't draw any conclusions from that screenshot. Works for me. I've also just added a CI to build it via GitHub Actions and that works too. Check out https://github.com/enlyze/Wizard-2020/blob/clang/.github/workflows/build.yml and https://github.com/enlyze/ghcr-windows-build-environment for details.

Closing this now. Please reopen if the issue persists.
